TEMPLATEROOT = ..

# object files

OBJS= main.o stupid_delay.o GPS.o simple_buffer.o UART.o stm32f0xx_hal_dma.o stm32f0xx_hal_rcc.o stm32f0xx_hal_gpio.o stm32f0xx_hal_uart.o stm32f0xx_hal_cortex.o stm32f0xx_hal.o stm32f0xx_hal_uart_ex.o SPI.o NRF24.o stm32f0xx_hal_spi.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
