TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -Os -g0
ASFLAGS = -Os -g0

# object files

OBJS= main.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
