TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O3 -g0
ASFLAGS = -g0

# object files

OBJS= stupid_delay.o  main.o UART.o simple_buffer.o GPS.o SPI.o NRF24.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
